// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/step-three/AgentPlanningDoc.tsx": () => import("../components/mockups/step-three/AgentPlanningDoc.tsx"),
  "./components/mockups/step-two/EmbedOrg.tsx": () => import("../components/mockups/step-two/EmbedOrg.tsx")
};
