// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/branding/TwitterBanner.tsx": () => import("../components/mockups/branding/TwitterBanner.tsx"),
  "./components/mockups/logo/LogoExplorer.tsx": () => import("../components/mockups/logo/LogoExplorer.tsx"),
  "./components/mockups/logo/LogoExplorer2.tsx": () => import("../components/mockups/logo/LogoExplorer2.tsx"),
  "./components/mockups/logo/LogoExplorer3.tsx": () => import("../components/mockups/logo/LogoExplorer3.tsx"),
  "./components/mockups/seo-templates/AutomationUseCase.tsx": () => import("../components/mockups/seo-templates/AutomationUseCase.tsx"),
  "./components/mockups/seo-templates/BlogPost.tsx": () => import("../components/mockups/seo-templates/BlogPost.tsx"),
  "./components/mockups/seo-templates/ComparisonPage.tsx": () => import("../components/mockups/seo-templates/ComparisonPage.tsx"),
  "./components/mockups/seo-templates/IndustryVertical.tsx": () => import("../components/mockups/seo-templates/IndustryVertical.tsx"),
  "./components/mockups/seo-templates/PillarGuide.tsx": () => import("../components/mockups/seo-templates/PillarGuide.tsx"),
  "./components/mockups/seo-landing/AiSmallBusiness.tsx": () => import("../components/mockups/seo-landing/AiSmallBusiness.tsx"),
  "./components/mockups/seo-landing/AiSmallBusinessV2.tsx": () => import("../components/mockups/seo-landing/AiSmallBusinessV2.tsx"),
  "./components/mockups/step-two/EmbedOrg.tsx": () => import("../components/mockups/step-two/EmbedOrg.tsx"),
  "./components/mockups/step-three/AgentPlanningDoc.tsx": () => import("../components/mockups/step-three/AgentPlanningDoc.tsx"),
  "./components/mockups/value-comparison/ValueComparison.tsx": () => import("../components/mockups/value-comparison/ValueComparison.tsx")
};
